/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSystemAdminRouteImport } from './routes/_authenticated/system-admin'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPatientHistoryRouteImport } from './routes/_authenticated/patient-history'
import { Route as AuthenticatedOrganizationSettingsRouteImport } from './routes/_authenticated/organization-settings'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedImportsRouteImport } from './routes/_authenticated/imports'
import { Route as AuthenticatedEmrTimelineRouteImport } from './routes/_authenticated/emr-timeline'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAccessControlRouteImport } from './routes/_authenticated/access-control'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemAdminRoute =
  AuthenticatedSystemAdminRouteImport.update({
    id: '/system-admin',
    path: '/system-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientHistoryRoute =
  AuthenticatedPatientHistoryRouteImport.update({
    id: '/patient-history',
    path: '/patient-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationSettingsRoute =
  AuthenticatedOrganizationSettingsRouteImport.update({
    id: '/organization-settings',
    path: '/organization-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportsRoute = AuthenticatedImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmrTimelineRoute =
  AuthenticatedEmrTimelineRouteImport.update({
    id: '/emr-timeline',
    path: '/emr-timeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccessControlRoute =
  AuthenticatedAccessControlRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/access-control': typeof AuthenticatedAccessControlRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emr-timeline': typeof AuthenticatedEmrTimelineRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/lab': typeof AuthenticatedLabRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/organization-settings': typeof AuthenticatedOrganizationSettingsRoute
  '/patient-history': typeof AuthenticatedPatientHistoryRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/system-admin': typeof AuthenticatedSystemAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/access-control': typeof AuthenticatedAccessControlRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emr-timeline': typeof AuthenticatedEmrTimelineRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/lab': typeof AuthenticatedLabRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/organization-settings': typeof AuthenticatedOrganizationSettingsRoute
  '/patient-history': typeof AuthenticatedPatientHistoryRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/system-admin': typeof AuthenticatedSystemAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/access-control': typeof AuthenticatedAccessControlRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emr-timeline': typeof AuthenticatedEmrTimelineRoute
  '/_authenticated/imports': typeof AuthenticatedImportsRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/organization-settings': typeof AuthenticatedOrganizationSettingsRoute
  '/_authenticated/patient-history': typeof AuthenticatedPatientHistoryRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/system-admin': typeof AuthenticatedSystemAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/access-control'
    | '/appointments'
    | '/automations'
    | '/billing'
    | '/dashboard'
    | '/emr-timeline'
    | '/imports'
    | '/lab'
    | '/modules'
    | '/organization-settings'
    | '/patient-history'
    | '/patients'
    | '/pharmacy'
    | '/prescriptions'
    | '/queue'
    | '/system-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/access-control'
    | '/appointments'
    | '/automations'
    | '/billing'
    | '/dashboard'
    | '/emr-timeline'
    | '/imports'
    | '/lab'
    | '/modules'
    | '/organization-settings'
    | '/patient-history'
    | '/patients'
    | '/pharmacy'
    | '/prescriptions'
    | '/queue'
    | '/system-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/access-control'
    | '/_authenticated/appointments'
    | '/_authenticated/automations'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/emr-timeline'
    | '/_authenticated/imports'
    | '/_authenticated/lab'
    | '/_authenticated/modules'
    | '/_authenticated/organization-settings'
    | '/_authenticated/patient-history'
    | '/_authenticated/patients'
    | '/_authenticated/pharmacy'
    | '/_authenticated/prescriptions'
    | '/_authenticated/queue'
    | '/_authenticated/system-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/system-admin': {
      id: '/_authenticated/system-admin'
      path: '/system-admin'
      fullPath: '/system-admin'
      preLoaderRoute: typeof AuthenticatedSystemAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient-history': {
      id: '/_authenticated/patient-history'
      path: '/patient-history'
      fullPath: '/patient-history'
      preLoaderRoute: typeof AuthenticatedPatientHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organization-settings': {
      id: '/_authenticated/organization-settings'
      path: '/organization-settings'
      fullPath: '/organization-settings'
      preLoaderRoute: typeof AuthenticatedOrganizationSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imports': {
      id: '/_authenticated/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AuthenticatedImportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emr-timeline': {
      id: '/_authenticated/emr-timeline'
      path: '/emr-timeline'
      fullPath: '/emr-timeline'
      preLoaderRoute: typeof AuthenticatedEmrTimelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access-control': {
      id: '/_authenticated/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AuthenticatedAccessControlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccessControlRoute: typeof AuthenticatedAccessControlRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmrTimelineRoute: typeof AuthenticatedEmrTimelineRoute
  AuthenticatedImportsRoute: typeof AuthenticatedImportsRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedOrganizationSettingsRoute: typeof AuthenticatedOrganizationSettingsRoute
  AuthenticatedPatientHistoryRoute: typeof AuthenticatedPatientHistoryRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedSystemAdminRoute: typeof AuthenticatedSystemAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccessControlRoute: AuthenticatedAccessControlRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmrTimelineRoute: AuthenticatedEmrTimelineRoute,
  AuthenticatedImportsRoute: AuthenticatedImportsRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedOrganizationSettingsRoute:
    AuthenticatedOrganizationSettingsRoute,
  AuthenticatedPatientHistoryRoute: AuthenticatedPatientHistoryRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedSystemAdminRoute: AuthenticatedSystemAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
