/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest, getRequestIP } from "@tanstack/react-start/server";
import { getSupabaseServerClient } from "./client.server";

type SessionClaims = {
  session_id?: string;
  sub?: string;
};

type ActiveRole = {
  role: string;
  custom_label: string | null;
};

function roleKeyFromRows(rows: ActiveRole[]) {
  const superAdmin = rows.find((row) => row.role === "admin" && row.custom_label === "super_admin");
  if (superAdmin) return "super_admin";
  const hospitalAdmin = rows.find(
    (row) => row.role === "admin" && row.custom_label === "hospital_admin",
  );
  if (hospitalAdmin) return "hospital_admin";
  const admin = rows.find((row) => row.role === "admin");
  if (admin) return "admin";
  const doctor = rows.find((row) => row.role === "doctor");
  if (doctor) return "doctor";
  const staff = rows.find((row) => row.role === "staff");
  if (staff) return "staff";
  const custom = rows.find((row) => row.role === "custom");
  return custom?.custom_label ?? "custom";
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const supabase = getSupabaseServerClient();
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser();

    if (error || !user) throw new Response("Unauthorized", { status: 401 });

    const { data: profile } = await supabase
      .from("profiles")
      .select("id, status")
      .eq("id", user.id)
      .maybeSingle();
    if ((profile as { status?: string } | null)?.status !== "active") {
      throw new Response("Unauthorized", { status: 401 });
    }

    const { data: roles } = await supabase
      .from("user_roles")
      .select("role, custom_label")
      .eq("user_id", user.id);
    const activeRoles = ((roles ?? []) as ActiveRole[]).filter(
      (row) => !row.custom_label?.startsWith("pending:"),
    );
    if (activeRoles.length === 0) throw new Response("Unauthorized", { status: 401 });

    const { data: claimsData } = await supabase.auth.getClaims();
    const claims = claimsData?.claims as SessionClaims | undefined;
    const sessionId = claims?.session_id;

    if (sessionId) {
      const db = supabase as any;
      const { data: trackedSession } = await db
        .from("user_sessions")
        .select("created_at, last_activity_at, revoked_at")
        .eq("id", sessionId)
        .eq("user_id", user.id)
        .maybeSingle();
      const roleKey = roleKeyFromRows(activeRoles);
      const { data: policy } = await db
        .from("role_session_policies")
        .select("idle_timeout_minutes, absolute_timeout_minutes")
        .eq("role", roleKey)
        .maybeSingle();

      if (
        trackedSession &&
        policy &&
        !(trackedSession as { revoked_at?: string | null }).revoked_at
      ) {
        const session = trackedSession as { created_at: string; last_activity_at: string };
        const limits = policy as {
          idle_timeout_minutes: number;
          absolute_timeout_minutes: number;
        };
        const now = Date.now();
        const idleMs = now - new Date(session.last_activity_at).getTime();
        const ageMs = now - new Date(session.created_at).getTime();
        const timedOut = idleMs > limits.idle_timeout_minutes * 60_000;
        const expired = ageMs > limits.absolute_timeout_minutes * 60_000;

        if (timedOut || expired) {
          await db
            .from("user_sessions")
            .update({
              revoked_at: new Date().toISOString(),
              revoked_reason: timedOut ? "idle_timeout" : "absolute_timeout",
            })
            .eq("id", sessionId);
          await supabase.auth.signOut();
          throw new Response("Session expired", { status: 401 });
        }

        if (idleMs > 60_000) {
          await db
            .from("user_sessions")
            .update({
              last_activity_at: new Date().toISOString(),
              ip_address: getRequestIP({ xForwardedFor: true }) ?? null,
              user_agent: getRequest().headers.get("user-agent"),
            })
            .eq("id", sessionId);
        }
      }
    }

    return next({
      context: {
        supabase,
        user,
        userId: user.id,
        role: roleKeyFromRows(activeRoles),
        roles: activeRoles,
        claims,
      },
    });
  },
);

export const requireRole = (...allowedRoles: string[]) =>
  createMiddleware({ type: "function" })
    .middleware([requireSupabaseAuth])
    .server(async ({ next, context }) => {
      if (!allowedRoles.includes(context.role)) throw new Response("Forbidden", { status: 403 });
      return next();
    });
